# Generated by Django 4.2.5 on 2023-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useproduct',
            name='isReturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useproduct',
            name='returnQuantity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
