# Generated by Django 4.2.5 on 2023-09-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_useproduct_isreturn_alter_useproduct_returnquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useproduct',
            old_name='returnQuantity',
            new_name='returnQuality',
        ),
        migrations.RenameField(
            model_name='useproduct',
            old_name='takenQuantity',
            new_name='takenQuality',
        ),
    ]
