# Generated by Django 4.2.5 on 2023-09-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_returnquantity_useproduct_returnquality_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useproduct',
            unique_together={('employe', 'product')},
        ),
    ]
